/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as LandingIndexRouteImport } from './routes/_landing.index'
import { Route as LabTestErrorRouteImport } from './routes/lab.test-error'
import { Route as LandingGettingStartedRouteImport } from './routes/_landing.getting-started'
import { Route as LabBlogIndexRouteImport } from './routes/lab.blog.index'
import { Route as LabBlogSlugRouteImport } from './routes/lab.blog.$slug'

const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LabTestErrorRoute = LabTestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => LabRoute,
} as any)
const LandingGettingStartedRoute = LandingGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => LandingRoute,
} as any)
const LabBlogIndexRoute = LabBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LabRoute,
} as any)
const LabBlogSlugRoute = LabBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/lab': typeof LabRouteWithChildren
  '/getting-started': typeof LandingGettingStartedRoute
  '/lab/test-error': typeof LabTestErrorRoute
  '/lab/': typeof LabIndexRoute
  '/lab/blog/$slug': typeof LabBlogSlugRoute
  '/lab/blog/': typeof LabBlogIndexRoute
}
export interface FileRoutesByTo {
  '/getting-started': typeof LandingGettingStartedRoute
  '/lab/test-error': typeof LabTestErrorRoute
  '/': typeof LandingIndexRoute
  '/lab': typeof LabIndexRoute
  '/lab/blog/$slug': typeof LabBlogSlugRoute
  '/lab/blog': typeof LabBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/_landing/getting-started': typeof LandingGettingStartedRoute
  '/lab/test-error': typeof LabTestErrorRoute
  '/_landing/': typeof LandingIndexRoute
  '/lab/': typeof LabIndexRoute
  '/lab/blog/$slug': typeof LabBlogSlugRoute
  '/lab/blog/': typeof LabBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/getting-started'
    | '/lab/test-error'
    | '/lab/'
    | '/lab/blog/$slug'
    | '/lab/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/getting-started'
    | '/lab/test-error'
    | '/'
    | '/lab'
    | '/lab/blog/$slug'
    | '/lab/blog'
  id:
    | '__root__'
    | '/_landing'
    | '/lab'
    | '/_landing/getting-started'
    | '/lab/test-error'
    | '/_landing/'
    | '/lab/'
    | '/lab/blog/$slug'
    | '/lab/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  LabRoute: typeof LabRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/lab/test-error': {
      id: '/lab/test-error'
      path: '/test-error'
      fullPath: '/lab/test-error'
      preLoaderRoute: typeof LabTestErrorRouteImport
      parentRoute: typeof LabRoute
    }
    '/_landing/getting-started': {
      id: '/_landing/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof LandingGettingStartedRouteImport
      parentRoute: typeof LandingRoute
    }
    '/lab/blog/': {
      id: '/lab/blog/'
      path: '/blog'
      fullPath: '/lab/blog/'
      preLoaderRoute: typeof LabBlogIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/blog/$slug': {
      id: '/lab/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/lab/blog/$slug'
      preLoaderRoute: typeof LabBlogSlugRouteImport
      parentRoute: typeof LabRoute
    }
  }
}

interface LandingRouteChildren {
  LandingGettingStartedRoute: typeof LandingGettingStartedRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingGettingStartedRoute: LandingGettingStartedRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface LabRouteChildren {
  LabTestErrorRoute: typeof LabTestErrorRoute
  LabIndexRoute: typeof LabIndexRoute
  LabBlogSlugRoute: typeof LabBlogSlugRoute
  LabBlogIndexRoute: typeof LabBlogIndexRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabTestErrorRoute: LabTestErrorRoute,
  LabIndexRoute: LabIndexRoute,
  LabBlogSlugRoute: LabBlogSlugRoute,
  LabBlogIndexRoute: LabBlogIndexRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  LabRoute: LabRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
