/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabRouteRouteImport } from './routes/lab/route'
import { Route as GettingStartedRouteRouteImport } from './routes/getting-started/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as GettingStartedIndexRouteImport } from './routes/getting-started/index'
import { Route as LabTestErrorRouteImport } from './routes/lab/test-error'
import { Route as LabBlogIndexRouteImport } from './routes/lab/blog/index'
import { Route as LabBlogSlugRouteImport } from './routes/lab/blog/$slug'

const LabRouteRoute = LabRouteRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRouteRoute = GettingStartedRouteRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRouteRoute,
} as any)
const GettingStartedIndexRoute = GettingStartedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GettingStartedRouteRoute,
} as any)
const LabTestErrorRoute = LabTestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabBlogIndexRoute = LabBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabBlogSlugRoute = LabBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LabRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/getting-started': typeof GettingStartedRouteRouteWithChildren
  '/lab': typeof LabRouteRouteWithChildren
  '/lab/test-error': typeof LabTestErrorRoute
  '/getting-started/': typeof GettingStartedIndexRoute
  '/lab/': typeof LabIndexRoute
  '/lab/blog/$slug': typeof LabBlogSlugRoute
  '/lab/blog/': typeof LabBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab/test-error': typeof LabTestErrorRoute
  '/getting-started': typeof GettingStartedIndexRoute
  '/lab': typeof LabIndexRoute
  '/lab/blog/$slug': typeof LabBlogSlugRoute
  '/lab/blog': typeof LabBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/getting-started': typeof GettingStartedRouteRouteWithChildren
  '/lab': typeof LabRouteRouteWithChildren
  '/lab/test-error': typeof LabTestErrorRoute
  '/getting-started/': typeof GettingStartedIndexRoute
  '/lab/': typeof LabIndexRoute
  '/lab/blog/$slug': typeof LabBlogSlugRoute
  '/lab/blog/': typeof LabBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/getting-started'
    | '/lab'
    | '/lab/test-error'
    | '/getting-started/'
    | '/lab/'
    | '/lab/blog/$slug'
    | '/lab/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lab/test-error'
    | '/getting-started'
    | '/lab'
    | '/lab/blog/$slug'
    | '/lab/blog'
  id:
    | '__root__'
    | '/'
    | '/getting-started'
    | '/lab'
    | '/lab/test-error'
    | '/getting-started/'
    | '/lab/'
    | '/lab/blog/$slug'
    | '/lab/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GettingStartedRouteRoute: typeof GettingStartedRouteRouteWithChildren
  LabRouteRoute: typeof LabRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/getting-started/': {
      id: '/getting-started/'
      path: '/'
      fullPath: '/getting-started/'
      preLoaderRoute: typeof GettingStartedIndexRouteImport
      parentRoute: typeof GettingStartedRouteRoute
    }
    '/lab/test-error': {
      id: '/lab/test-error'
      path: '/test-error'
      fullPath: '/lab/test-error'
      preLoaderRoute: typeof LabTestErrorRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/blog/': {
      id: '/lab/blog/'
      path: '/blog'
      fullPath: '/lab/blog/'
      preLoaderRoute: typeof LabBlogIndexRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/blog/$slug': {
      id: '/lab/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/lab/blog/$slug'
      preLoaderRoute: typeof LabBlogSlugRouteImport
      parentRoute: typeof LabRouteRoute
    }
  }
}

interface GettingStartedRouteRouteChildren {
  GettingStartedIndexRoute: typeof GettingStartedIndexRoute
}

const GettingStartedRouteRouteChildren: GettingStartedRouteRouteChildren = {
  GettingStartedIndexRoute: GettingStartedIndexRoute,
}

const GettingStartedRouteRouteWithChildren =
  GettingStartedRouteRoute._addFileChildren(GettingStartedRouteRouteChildren)

interface LabRouteRouteChildren {
  LabTestErrorRoute: typeof LabTestErrorRoute
  LabIndexRoute: typeof LabIndexRoute
  LabBlogSlugRoute: typeof LabBlogSlugRoute
  LabBlogIndexRoute: typeof LabBlogIndexRoute
}

const LabRouteRouteChildren: LabRouteRouteChildren = {
  LabTestErrorRoute: LabTestErrorRoute,
  LabIndexRoute: LabIndexRoute,
  LabBlogSlugRoute: LabBlogSlugRoute,
  LabBlogIndexRoute: LabBlogIndexRoute,
}

const LabRouteRouteWithChildren = LabRouteRoute._addFileChildren(
  LabRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GettingStartedRouteRoute: GettingStartedRouteRouteWithChildren,
  LabRouteRoute: LabRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
